include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_relative_imports # makes it easier to differentiate local and library imports at a glance

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "**/*.mocks.dart" # generated files (mockito)
    - "**/*.g.dart"

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-arguments: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
  anti-patterns:
    - long-method
    - long-parameter-list

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
