name: canteen_mgmt_frontend
description: Frontend for our canteen management system.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  qr_code_scanner: ^0.6.1
  http: ^0.13.4
  shared_preferences: ^2.0.12

  # navigation
  beamer: ^1.2.0

  # service locator (allows for easy injection)
  get_it: ^7.2.0

  # image picker for profile photo
  image_picker: ^0.8.4+6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # static analysis tools
  flutter_lints: ^1.0.0
  dart_code_metrics: ^4.8.1

  # convert flutter test results (json) to JUnit format
  junitreport: ^2.0.2

  mockito: ^5.0.17

  # code generation, required for mockito
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - canteen.p12
    - assets/graphics/
