version: 2.1

orbs:
  flutter: circleci/flutter@1.0.1
  browser-tools: circleci/browser-tools@1.2.3

jobs:
  build:
    docker:
      # has browsers (including chromedriver) preinstalled
      - image: cimg/android:2021.10.2-browsers
      # alternative: cirrusci/flutter:2.8.1 see https://hub.docker.com/r/cirrusci/flutter/
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - flutter/install_sdk_and_pub:
          flutter_version: 2.8.1
      - run:
          name: Build web
          command: flutter build web --web-renderer html
      - run:
          name: Compress Artifacts
          command: zip -r web.zip .
          working_directory: build/web
      - store_artifacts:
          path: build/web/web.zip

  run-widget-tests:
    docker:
      - image: cimg/android:2021.10.2-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - flutter/install_sdk_and_pub:
          flutter_version: 2.8.1
      - run:
          name: Create reports directory
          command: mkdir reports
      - run:
          name: Run Widget tests
          # creates test report (reports/tests.jsonl) and coverage report (coverage/lcov.info)
          # note coverage will not be reported for files that are not tested at all (see )
          command: flutter test --coverage --reporter json > reports/tests.jsonl

      - store_artifacts:
          # regarding format, see https://github.com/dart-lang/test/blob/master/pkgs/test/doc/json_reporter.md
          path: reports/tests.jsonl
      - run:
          name: Generate JUnit XML report
          # see https://pub.dev/packages/junitreport
          command: flutter pub run junitreport:tojunit -i reports/tests.jsonl -o reports/tests.xml
      - store_test_results:
          path: reports/tests.xml
      - store_artifacts:
          path: reports/tests.xml

      - store_artifacts:
          path: coverage/lcov.info
      - run:
          name: Install lcov (for genhtml)
          command: sudo apt-get -y update && sudo apt-get -y install lcov
      - run:
          name: Generate HTML coverage report
          # see https://stackoverflow.com/questions/50789578/how-can-the-code-coverage-data-from-flutter-tests-be-displayed
          command: genhtml coverage/lcov.info -o coverage/html
      - run:
          name: Compress Artifacts
          command: zip -r coverage.zip .
          working_directory: coverage/html
      - store_artifacts:
          path: coverage/html/coverage.zip

  run-integration-tests:
    docker:
      - image: cimg/android:2021.10.2-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - flutter/install_sdk_and_pub:
          flutter_version: 2.8.1
      - run:
          name: Start chromedriver
          command: chromedriver --port=4444
          background: true
      - run:
          name: Run Integration tests
          # `flutter drive` does not support machine-readable reports
          # regarding coverage see also https://stackoverflow.com/questions/57933204/flutter-driver-test-coverage-report
          command: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/demo_test.dart -d web-server --web-renderer html

workflows:
  test-and-build:
    jobs:
      - run-widget-tests
      - run-integration-tests
      - build
